version: "3"

services:
  backend:
    build: ./backend/
    container_name: backend
    ports:
      - 8080:8080

  front:
    build: ./front/
    container_name: front
    ports:
        - 4200:4200
